### ISSUE TITLE
Kinetic modeling vignette uses parameter name.init, which no longer exists

### ISSUE THREAD

**Issue by Lygeri-Sakellaridi** [erhard-lab/grandR#17]
Hello!

The kinetic modeling vignette includes the following line:

sars <- CalibrateEffectiveLabelingTimeKineticFit(sars,steady.state=list(Mock=TRUE,SARS=FALSE),name.init = "init_time")

name.init is not a parameter that can be given to CalibrateEffectiveLabelingTimeKineticFit

I'm assuming it was renamed to something (time.name?)

**Comment by florianerhard** [comment]
Fixed
